import { evaluatePolicy, type PolicyFinding } from "@/lib/policy";
import type { AutoMcpSpec } from "@/lib/spec";

export type GeneratedManifest = {
  name: string;
  capabilities: string[];
  operations: Array<{ name: string; destructive: boolean }>;
  sourceHost: string | null;
  credentialReference: string | null;
};
export type CompiledProject = { files: Record<string, string>; manifest: GeneratedManifest };
export class CompileError extends Error {
  constructor(readonly findings: PolicyFinding[]) { super("The project spec did not pass security policy."); }
}

const q = (value: unknown) => JSON.stringify(value, null, 2);

function serverSource(spec: AutoMcpSpec): string {
  const toolBlocks = spec.operations.map((operation) => `
server.tool("${operation.name}", "${operation.summary}", { query: z.string().min(1).describe("User query or identifier") }, async ({ query }) => ({
  content: [{ type: "text", text: JSON.stringify({ operation: "${operation.name}", query, source: process.env.SOURCE_BASE_URL }) }],
  structuredContent: { operation: "${operation.name}", query },
}));`).join("\n");
  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer({ name: ${JSON.stringify(spec.name)}, version: "0.1.0" });
${toolBlocks}
server.resource("catalog", "catalog://products", { description: "Read-only catalog context" }, async () => ({ contents: [{ uri: "catalog://products", text: "Connect your source adapter to provide catalog content." }] }));
server.prompt("catalog-assistant", "Help a user discover catalog products", () => ({ messages: [{ role: "user", content: { type: "text", text: "Help me find the right catalog product." } }] }));

await server.connect(new StdioServerTransport());
`;
}

export function compileProject(spec: AutoMcpSpec): CompiledProject {
  const report = evaluatePolicy(spec);
  if (!report.allowed) throw new CompileError(report.findings);
  const sourceHost = spec.source.url ? new URL(spec.source.url).host : null;
  const manifest: GeneratedManifest = {
    name: spec.name,
    capabilities: spec.capabilities,
    operations: spec.operations.map((operation) => ({ name: operation.name, destructive: operation.kind === "write" })),
    sourceHost,
    credentialReference: spec.credential ? `${spec.credential.provider}:${spec.credential.key}` : null,
  };
  return {
    manifest,
    files: {
      "package.json": q({ name: spec.name, private: true, type: "module", scripts: { start: "tsx src/server.ts", test: "vitest run" }, dependencies: { "@modelcontextprotocol/sdk": "^1.29.0", zod: "^4.3.6" }, devDependencies: { tsx: "^4.20.0", typescript: "^5.9.3", vitest: "^4.1.10" } }),
      "src/server.ts": serverSource(spec),
      "src/policy.ts": `export const allowedSourceHost = ${JSON.stringify(sourceHost)};\nexport const credentialReference = ${JSON.stringify(manifest.credentialReference)};\n`,
      "tests/server.test.ts": `import { describe, expect, it } from "vitest";\ndescribe("${spec.name}", () => it("declares an MCP server", () => expect(${JSON.stringify(spec.name)}).toMatch(/mcp/)));\n`,
      ".env.example": `SOURCE_BASE_URL=${spec.source.url ?? "https://api.example.com"}\n${spec.credential ? `${spec.credential.key}=replace-with-secret\n` : ""}`,
      "automcp.manifest.json": q(manifest),
      "README.md": `# ${spec.name}\n\nGenerated by AutoMCP. Run locally with \`npm install && npm start\` using the MCP stdio transport.\n\n## Security\n\nSet secrets in your environment; do not commit them. The manifest records a credential reference, not a credential value. Remote deployments should use Streamable HTTP with OAuth 2.1 and separate upstream credentials.\n`,
      "DEPLOYMENT.md": "Deploy remote MCP servers with Streamable HTTP, Host header validation, OAuth 2.1, PKCE, audience validation, and a separate upstream token. Do not forward the MCP client token.\n",
    },
  };
}
