import { z } from "zod";

export const DeploymentModeSchema = z.enum(["local", "cloud", "hybrid"]);
export const CapabilitySchema = z.enum(["tool", "resource", "prompt", "webhook", "job", "workflow"]);
export const SourceKindSchema = z.enum(["openapi", "rest", "graphql", "file"]);
export const CredentialReferenceSchema = z.object({
  provider: z.string().min(1).max(100),
  key: z.string().min(1).max(160),
}).strict();

export const AutoMcpSpecSchema = z.object({
  name: z.string().regex(/^[a-z][a-z0-9-]{2,62}$/),
  description: z.string().min(12).max(500),
  intent: z.string().min(8).max(1_000),
  deploymentMode: DeploymentModeSchema.default("hybrid"),
  advancedCapabilities: z.boolean().default(false),
  source: z.object({
    kind: SourceKindSchema,
    url: z.string().url().optional(),
    label: z.string().min(1).max(120),
  }).strict(),
  credential: CredentialReferenceSchema.optional(),
  capabilities: z.array(CapabilitySchema).min(1).max(6),
  operations: z.array(z.object({
    name: z.string().regex(/^[a-z][a-z0-9_]{2,62}$/),
    summary: z.string().min(3).max(240),
    kind: z.enum(["read", "write"]),
  }).strict()).min(1).max(24),
}).strict();

export type AutoMcpSpec = z.infer<typeof AutoMcpSpecSchema>;
export type Capability = z.infer<typeof CapabilitySchema>;

export function createSampleSpec(): AutoMcpSpec {
  return {
    name: "catalog-mcp",
    description: "A safe product catalog MCP server generated by AutoMCP.",
    intent: "Search the catalog and read a product by id for customer support.",
    deploymentMode: "hybrid",
    advancedCapabilities: false,
    source: { kind: "openapi", url: "https://api.example.com/openapi.json", label: "Catalog OpenAPI" },
    credential: { provider: "environment", key: "CATALOG_API_TOKEN" },
    capabilities: ["tool", "resource", "prompt"],
    operations: [
      { name: "search_products", summary: "Search the product catalog", kind: "read" },
      { name: "get_product", summary: "Read a product by id", kind: "read" },
    ],
  };
}

export function parseSpec(input: unknown): AutoMcpSpec {
  return AutoMcpSpecSchema.parse(input);
}
